### PR TITLE
Centered images in docs

### PR DESCRIPTION
**Pull request by olehermanse**
**Before:**

before

**After:**

centered

### CODE REVIEW

**Comment by nickanderson** [comment]
I have no opinion.

**Review by nickanderson — APPROVED** [review]

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by olehermanse** [comment]
@cf-bottom please try to build in jenkins again

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7634/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7634/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7634/

**Documentation:** http://buildcache.cfengine.com/packages/build-documentation-pr/jenkins-pr-pipeline-7634/output/_site/

**Pull request merged**
