### PR TITLE
Update manual version to 3.9.

### PR DESCRIPTION
**Pull request by kacf**

### CODE REVIEW

**Comment by kacf** [comment]
@nickanderson: ping

**Comment by kacf** [comment]
@nickanderson, @michaelclelland 

I feel a bit in deep water here, just changing a bunch of places that had master listed. I guess Nick has done most of this before, does it look sane?

**Comment by michaelclelland** [comment]
Looking at 3.8 and 3.7, I don't think cfdoc_git.py needs changed from master to 3.9

**Comment by kacf** [comment]
Alright, removed the Python part.

**Comment by nickanderson** [comment]
I intend on looking at the docs as soon as I can get to it.

**Pull request merged**
