### PR TITLE
Relax permissions for cleanup

### PR DESCRIPTION
**Pull request by Lex-2008**
Otherwise, they can't be deleted afterwards

Ticket: ENT-7467

### CODE REVIEW

**Comment by Lex-2008** [comment]
test build: https://ci.cfengine.com/job/docs-pr/43/

**Comment by vpodzime** [comment]
Looks like a WIP to me.

**Review by vpodzime — APPROVED** [review]
Looks good to me.

**Comment by Lex-2008** [comment]
Instead of copying everything into the container (as discussed before on Slack), I've decided to chmod everything to 777. Issue with copying everything was that it complicated code too much:
* the artifacts to be uploaded to buildcache were generated inside the container.
* so cleanup should happen after they're uploaded to buildcache
* but if uploading fails - cleanup should still succeed
While doable, sounds more fragile than an extra chmod

**Pull request merged**
