### PR TITLE
ENT-4396 Fix pdf generation - master

### PR DESCRIPTION
**Pull request by Lex-2008**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a pull request! Maybe @olehermanse can review this?

**Comment by Lex-2008** [comment]
It doesn't. Instead, `weasyprint` that we use to generate it, fails:
```
14:24:34 + weasyprint http://localhost:8000/docs/master/reference-functions-mergedata.html /home/jenkins/workspace/build-documentation-master/label/DOCUMENTATION_x86_64_linux_ubuntu_16/documentation-generator/_site/pdf/reference-functions-mergedata.pdf
14:24:34 Traceback (most recent call last):
14:24:34   File "/usr/local/bin/weasyprint", line 7, in <module>
14:24:34     from weasyprint.__main__ import main
14:24:34   File "/usr/local/lib/python3.5/dist-packages/weasyprint/__init__.py", line 393, in <module>
14:24:34     from .css import preprocess_stylesheet  # noqa
14:24:34   File "/usr/local/lib/python3.5/dist-packages/weasyprint/css/__init__.py", line 26, in <module>
14:24:34     from . import computed_values
14:24:34   File "/usr/local/lib/python3.5/dist-packages/weasyprint/css/computed_values.py", line 17, in <module>
14:24:34     from .. import text
14:24:34   File "/usr/local/lib/python3.5/dist-packages/weasyprint/text.py", line 21, in <module>
14:24:34     True: cairo.Context(cairo.ImageSurface(cairo.FORMAT_ARGB32, 1, 1)),
14:24:34 AttributeError: module 'cairocffi' has no attribute 'Context'
```

**Comment by Lex-2008** [comment]
@nickanderson : pdfs are there! For master branch only, for now.
For page with URL like this:
```
https://docs.cfengine.com/docs/master/guide.html
```
PDF is located here:
```
https://docs.cfengine.com/docs/master/pdf/guide.pdf
```
Note that it will likely be wiped on next master build.

**Comment by nickanderson** [comment]
Nice, i am surprised at how nice they look.

Some issues:
- Some text runs off the page
- Footers on each page are ugly
- Lack of style for code

Do we care to have a pdf for each page? What about just a pdf of the printable reference since it's all in one page?

**Comment by olehermanse** [comment]
Please squash before merging.

**Comment by Lex-2008** [comment]
Agreed. Also would be good if it didn't break Jenkins :)

**Pull request closed without merging**
