### PR TITLE
Update docs container to Ubuntu 22

### PR DESCRIPTION
**Pull request by Lex-2008**
Ticket: ENT-8470

Changes:
* make install script fail on error (set -e)
* use gpg2 instead of gpg
* install ruby without rubygems (before rvm tried to install rubygems
  and failed and we ignored it)
* install ruby without openssl (because ruby compiled against openssl
  1.0 and modern distros don't ship it. And we don't need openssl in
  ruby anyway)
* use python3 instead of python2
* Changed Python scripts from 2 to 3 using 2to3.py

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom: will it build?

**Comment by Lex-2008** [comment]
testbuild: https://ci.cfengine.com/view/Documentation/job/fast-build-and-deploy-docs-master/44
results will appear somewhere in http://buildcache.cloud.cfengine.com/packages/build-documentation-pr/

**Comment by Lex-2008** [comment]
looks like the above message is not new: if you open markdown-cheatsheet.html and scroll down to (or rather Ctrl+F for) "body delete tidy from lib/files.cf in the MPF" you will see the same unexpanded macro:
```
[%CFEngine_include_MPF_snippet(lib/files.cf, body\s+delete\s+tidy, })%]
```
so all's good!

**Review by vpodzime — APPROVED** [review]
Looks good to me. Let me know when I can remove the old `docs` container (and everything it was build on/from).

**Pull request merged**
